name: fmt

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Format
        run: cargo +nightly fmt -- --check
        working-directory: src
